version: '3'

services:
  speedtest:
    restart: always
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      - "SPEEDTEST_INTERVAL=900"
      - "SPEEDTEST_HOST=local"
    depends_on:
      - influxdb