version: '3'

services:
  influxdb:
    container_name: influxdb
    restart: always
    image: influxdb:1.8
    ports:
      - "8086"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
      - "./db_init.iql:/docker-entrypoint-initdb.d/db_init.iql"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"

  grafana:
    restart: always
    image: grafana/grafana:6.7.2
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb