version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports: 
      - "80:8080"
    depends_on:
      - grafana
      - hivemq-mqtt-web-client
      - node-red
    

  influxdb:
    container_name: influxdb
    restart: always
    image: influxdb:1.8
    ports:
      - "8086"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
      - "./db_init.iql:/docker-entrypoint-initdb.d/db_init.iql"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"

  grafana:
    restart: always
    image: grafana/grafana:6.7.2
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000"
    environment:
      # required because grafana is behind nginx
      - "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb